In [2]:
import pickle as p
import networkx as nx
import numpy as np

In [32]:
sing_graph = p.load(open("./data/OASIS_full_batch/modified_graphs/graph_0.gpickle", "rb" ))

In [ ]:
# Generate the graph
# g, adj, protS, dict_s = getGraph_fairwalk(sizes=sizes, probs=probs, choice=method)
# nx.set_node_attributes(g,dict_s,'sensitive_attr')
# attr_comm = [{i for i in dict_s if dict_s[i]==0},{i for i in dict_s if dict_s[i]==1}] #communities on basis of attribute

# dens.append(nx.density(g))
# assort.append(nx.algorithms.assortativity.degree_pearson_correlation_coefficient(g)) #Compute degree assortativity of graph.
# assort_attributes.append(nx.attribute_assortativity_coefficient(g, 'sensitive_attr')) # assortavity with attributes
# clustering.append(nx.algorithms.cluster.average_clustering(g))
# modularity.append(nx.algorithms.community.modularity(g,attr_comm))

In [ ]:
nx.density(sing_graph)

In [ ]:
nx.algorithms.cluster.average_clustering(sing_graph)

In [ ]:
#nx.attribute_assortativity_coefficient(sing_graph,'')

In [ ]:
sing_graph.nodes.data()

In [33]:
def remove_dummy_nodes(graph):
    G = graph.copy()
    to_remove = []
    for (p, d) in G.nodes(data=True):
        if d['is_dummy'] == True:
            to_remove.append(p)
    G.remove_nodes_from(to_remove)
    return G

In [34]:
# g = sing_graph

In [35]:
real_graph = remove_dummy_nodes(sing_graph)

In [36]:
real_graph.nodes

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82))

In [38]:
sing_graph.nodes

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100))

In [10]:
ground_truth = np.load("ground_truth.npy")

In [36]:
gtpm = np.zeros((1, 89), dtype=int)

In [39]:
gtpm[0,:] = ground_truth[0][0]

In [47]:
ground_truth[2][1]

array([84, 68, 80, 23,  9, 42, 28, 33, 32, 75, 17, 41, 12, 24, 65, 29, 30,
       43, 13,  7, 88, 27, 56, 21,  6, 16, 48, 63, 15, 14, 37, 59, 38, 18,
       52, 83, 31, 22, 69, 73, 46, 44, 54, 62, 36, 64, 55,  5, 86, 82,  2,
        8, 49, 71, 78, 47, 50, 57, 51, 72, 77, 87, 67, 25,  3, 26, 19, 11,
        0, 79, 35,  1, 85, 10, 40, 53, 66, 60,  4, 70, 45, 81, 20, 74, 34,
       61, 39, 58, 76])

In [51]:
perm_mat_1 = ground_truth[1][2]
perm_mat_2 = ground_truth[2][1]

result_perm = np.zeros((perm_mat_1.shape[0],), dtype=int)

for node_reference, node_noisy_1 in enumerate(perm_mat_1):
    # get the corresponding node in the second graph
    node_noisy_2 = perm_mat_2[node_reference]

    # Fill the result
    result_perm[node_noisy_1] = node_noisy_2

result_perm

array([34,  0, 45, 21, 75, 54, 15, 18, 38, 53, 43, 44, 12,  6, 26, 14, 37,
       62, 24, 33, 76, 63, 50, 27, 28, 30, 86, 25, 29, 65, 22, 72, 69, 13,
       49, 74, 59, 56, 79, 10, 55, 36, 78, 67, 31,  3, 47, 42, 39, 20, 80,
       32, 82,  1,  4,  5,  2, 57,  8, 85, 60, 58, 11, 16, 23, 48,  7, 41,
       84, 70, 83, 68, 61, 17, 46, 71, 19, 77,  9, 35, 64, 81, 88, 40, 52,
       87, 73, 51, 66])

In [80]:
perm_mat_1

array([68, 71, 50, 64, 78, 47, 24, 19, 51,  4, 73, 67, 12, 18, 29, 28, 25,
       10, 33, 66, 82, 23, 37,  3, 13, 63, 65, 21,  6, 15, 16, 36,  8,  7,
       84, 70, 44, 30, 32, 86, 74, 11,  5, 17, 41, 80, 40, 55, 26, 52, 56,
       58, 34, 75, 42, 46, 22, 57, 87, 31, 77, 85, 43, 27, 45, 14, 76, 62,
        1, 38, 79, 53, 59, 39, 83,  9, 88, 60, 54, 69,  2, 81, 49, 35,  0,
       72, 48, 61, 20])

In [77]:
perm_mat_2

array([84, 68, 80, 23,  9, 42, 28, 33, 32, 75, 17, 41, 12, 24, 65, 29, 30,
       43, 13,  7, 88, 27, 56, 21,  6, 16, 48, 63, 15, 14, 37, 59, 38, 18,
       52, 83, 31, 22, 69, 73, 46, 44, 54, 62, 36, 64, 55,  5, 86, 82,  2,
        8, 49, 71, 78, 47, 50, 57, 51, 72, 77, 87, 67, 25,  3, 26, 19, 11,
        0, 79, 35,  1, 85, 10, 40, 53, 66, 60,  4, 70, 45, 81, 20, 74, 34,
       61, 39, 58, 76])

In [81]:
result_perm

array([34,  0, 45, 21, 75, 54, 15, 18, 38, 53, 43, 44, 12,  6, 26, 14, 37,
       62, 24, 33, 76, 63, 50, 27, 28, 30, 86, 25, 29, 65, 22, 72, 69, 13,
       49, 74, 59, 56, 79, 10, 55, 36, 78, 67, 31,  3, 47, 42, 39, 20, 80,
       32, 82,  1,  4,  5,  2, 57,  8, 85, 60, 58, 11, 16, 23, 48,  7, 41,
       84, 70, 83, 68, 61, 17, 46, 71, 19, 77,  9, 35, 64, 81, 88, 40, 52,
       87, 73, 51, 66])

In [82]:
import scipy.io as sio

In [83]:
affi_0_1 = sio.loadmat('affinity_0_1.mat')

In [87]:
affi_0_1['kE12'].shape

(261, 261)

In [91]:
#affi_0_1

In [92]:
per_mat = np.load("noise_1000,outliers_0/ground_truth.npy")

In [100]:
per_mat[0][2]

array([ 6,  7,  1, 19, 10,  3, 15, 13, 12, 18,  2,  0,  9,  5, 14,  4, 11,
       17,  8, 16])

In [104]:
per_mat[2][0]

array([11,  2, 10,  5, 15, 13,  0,  1, 18, 12,  4, 16,  8,  7, 14,  6, 19,
       17,  9,  3])

In [5]:
e = np.array(list(range(0, 0, 5)))

In [6]:
e

array([], dtype=float64)

In [12]:
g = nx.read_gpickle("graph_25.gpickle")

In [13]:
len(g.nodes())

72

In [15]:
g.nodes()

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71))