In [1]:
import sys
sys.path.extend(['/home/rohit/PhD_Work/GM_my_version/Graph_matching'])
import tools.graph_visu as gv
import tools.graph_processing as gp
import slam.io as sio
import numpy as np
import networkx as nx

In [2]:
path_to_graphs = '../data/simu_graph/0/test/0/noise_1400,outliers_8/graphs'
gt = np.load('../data/simu_graph/0/test/0/noise_1400,outliers_8/ground_truth.npy')
file_template_mesh = '../data/template_mesh/lh.OASIS_testGrp_average_inflated.gii'
file_sphere_mesh = '../data/template_mesh/ico100_7.gii'

In [3]:
list_graphs = gp.load_graphs_in_list(path_to_graphs)

In [25]:
outliers_label = -1

In [26]:
gt_01 = gt[0][1]
gt_02 = gt[0][2]
gt_03 = gt[0][3]
gt_04 = gt[0][4]

g = list_graphs[0]
g1 = list_graphs[1]
g2 = list_graphs[2]
g3 = list_graphs[3]
g4 = list_graphs[4]

dict_lab = {}
for n, node in enumerate(g1.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_01[node]] = {'label_gt':node}
nx.set_node_attributes(g1,dict_lab)

dict_lab = {}
for n, node in enumerate(g2.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_02[node]] = {'label_gt':node}
nx.set_node_attributes(g2,dict_lab)

dict_lab = {}
for n, node in enumerate(g3.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_03[node]] = {'label_gt':node}
nx.set_node_attributes(g3,dict_lab)

dict_lab = {}
for n, node in enumerate(g4.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_04[node]] = {'label_gt':node}
nx.set_node_attributes(g4,dict_lab)

dict_lab = {}
for n, node in enumerate(g.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[node] = {'label_gt':node}
nx.set_node_attributes(g,dict_lab)

In [27]:
gx = nx.relabel.convert_node_labels_to_integers(g1)
gx.nodes(data=True)

NodeDataView({0: {'coord': array([-32.62546432, -30.49374769, -89.47463568]), 'label_gt': 6}, 1: {'coord': array([ 94.90147083, -23.6980305 ,  20.78735637]), 'label_gt': -1}, 2: {'coord': array([-74.54044656,  50.24596227,  43.80713528]), 'label_gt': -1}, 3: {'coord': array([43.90688274, 88.12676938, 17.48880118]), 'label_gt': 4}, 4: {'coord': array([ -9.28207078, -99.25978348,   7.83189291]), 'label_gt': 0}, 5: {'coord': array([ 48.60140059, -44.88430711, -74.98868472]), 'label_gt': -1}, 6: {'coord': array([ 69.77960989, -71.60871737,   1.73136945]), 'label_gt': 8}, 7: {'coord': array([-70.28062179,  70.62715071,   8.51115645]), 'label_gt': 7}, 8: {'coord': array([-52.34375377, -22.393685  ,  82.21103523]), 'label_gt': -1}, 9: {'coord': array([ 16.76202035, -36.18698447,  91.70352681]), 'label_gt': 9}, 10: {'coord': array([-49.17804745,  82.07633359, -29.06879965]), 'label_gt': -1}, 11: {'coord': array([ 73.934375  , -28.16643084,  61.15848565]), 'label_gt': 13}, 12: {'coord': array([

In [29]:
# nx.get_node_attributes(g,'coord').values()

In [28]:
for ind in gt_02:
    print(g2.nodes.data()[ind])

{'coord': array([ -8.69066969, -99.61347477,   1.27589359]), 'label_gt': 0}
{'coord': array([-14.81124884,  64.91184598,  74.61286189]), 'label_gt': 1}
{'coord': array([-20.8787086 ,  96.16820935,  17.76949741]), 'label_gt': 2}
{'coord': array([-36.94592117, -51.91923021,  77.06745385]), 'label_gt': 3}
{'coord': array([41.32935546, 87.95926412, 23.55954653]), 'label_gt': 4}
{'coord': array([ 24.9600015 , -95.36526599,  16.80667626]), 'label_gt': 5}
{'coord': array([-31.12708379, -22.97149931, -92.21396247]), 'label_gt': 6}
{'coord': array([-69.51994188,  71.01383314,  11.13612074]), 'label_gt': 7}
{'coord': array([ 72.6356404 , -68.25163855,   8.11033772]), 'label_gt': 8}
{'coord': array([ 14.00324755, -36.50232723,  92.04069298]), 'label_gt': 9}
{'coord': array([-47.84250124, -84.70940554, -23.13896472]), 'label_gt': 10}
{'coord': array([-84.20397703,  -4.44431723, -53.75814632]), 'label_gt': 11}
{'coord': array([-94.73367317,  31.29147907,  -6.80988295]), 'label_gt': 12}
{'coord': ar

In [10]:
sphere_mesh = sio.load_mesh(file_sphere_mesh)
mesh = gv.reg_mesh(sio.load_mesh(file_template_mesh))
gp.sphere_nearest_neighbor_interpolation(g, sphere_mesh)
gp.sphere_nearest_neighbor_interpolation(g1, sphere_mesh)

In [179]:
nodes_coords = gp.graph_nodes_to_coords(g, 'ico100_7_vertex_index', sphere_mesh)
nodes_coords_1 = gp.graph_nodes_to_coords(g1, 'ico100_7_vertex_index', sphere_mesh)

In [23]:
counter = 0
rest = []
for i in range(len(g.nodes)):
    for ind in gt_01:
        if(g.nodes.data()[i]['label_gt'] == g1.nodes.data()[ind]['label_gt']):
            print(g.nodes.data()[i]['coord'],g1.nodes.data()[ind]['coord'])
            counter+=1
print(counter)

[ -8.29375734 -99.58600481   3.72038116] [ -9.28207078 -99.25978348   7.83189291]
[-11.96701424  65.4787652   74.62788941] [-19.39228571  69.60576829  69.13014014]
[-25.06130415  95.60418922  15.2239955 ] [-25.30512161  95.67896948  14.32430169]
[-36.95462701 -52.8159162   76.45151757] [-42.55639928 -54.45934114  72.27124631]
[42.60480034 87.95995566 21.16310915] [43.90688274 88.12676938 17.48880118]
[ 24.36019656 -95.13667031  18.85722104] [ 28.26062488 -93.99886388  19.11937947]
[-30.4412485  -26.82708365 -91.39823835] [-32.62546432 -30.49374769 -89.47463568]
[-70.04157873  70.43770444  11.51985424] [-70.28062179  70.62715071   8.51115645]
[ 71.22425583 -70.1867875    0.95929233] [ 69.77960989 -71.60871737   1.73136945]
[ 16.29928024 -35.40847182  92.09002979] [ 16.76202035 -36.18698447  91.70352681]
[-50.03733913 -84.16323567 -20.31783587] [-47.92418327 -83.28190631 -27.70192662]
[-83.34326539  -7.02261683 -54.81407635] [-79.55158573 -11.21003384 -59.54729506]
[-93.32844935  35.8005

In [15]:
un = nx.disjoint_union(g,g1)

In [40]:
for i in un.nodes():
    if((un.nodes.data()[i]['label']==50)):
       print(un.nodes.data()[i]['coord'])

[-56.11889642  25.04223002 -78.88951883]
[  2.77552172  97.88816609 -20.25347916]
[90.66891087 41.1681157  -9.18340084]
[-59.3130305   62.22627475  51.08674138]
[-16.49106543 -91.55535387  36.68326511]
[ 33.0934391  -78.95991037 -51.67356038]
[99.23325098 -8.58575806  8.89081878]
[62.88857825 58.68303726 51.00321424]
[ 76.43996182 -59.14811233 -25.65995021]
[-41.37398695 -14.95721347  89.80242184]
[-56.01050275 -81.91700632  12.34615961]
[  2.33495907 -88.65652333  46.20139432]
[ 34.32323732 -81.26778022 -47.0899488 ]
[ 24.10658203  22.49024288 -94.40901269]
[-30.7927306   65.37255605  69.12479047]
[ 50.5466927   38.5684428  -77.18488892]
