In [27]:
import sys
sys.path.extend(['/home/rohit/PhD_Work/GM_my_version/Graph_matching'])
import tools.graph_visu as gv
import tools.graph_processing as gp
import slam.io as sio
import numpy as np
import networkx as nx
from graph_generation.load_graphs_and_create_metadata import dataset_metadata


In [3]:
path_to_graphs = '../data/simu_graph/0/test/0/noise_1400,outliers_8/graphs'
gt = np.load('../data/simu_graph/0/test/0/noise_1400,outliers_8/ground_truth.npy')
file_template_mesh = '../data/template_mesh/lh.OASIS_testGrp_average_inflated.gii'
file_sphere_mesh = '../data/template_mesh/ico100_7.gii'

In [4]:
list_graphs = gp.load_graphs_in_list(path_to_graphs)

In [25]:
outliers_label = -1

In [26]:
gt_01 = gt[0][1]
gt_02 = gt[0][2]
gt_03 = gt[0][3]
gt_04 = gt[0][4]

g = list_graphs[0]
g1 = list_graphs[1]
g2 = list_graphs[2]
g3 = list_graphs[3]
g4 = list_graphs[4]

dict_lab = {}
for n, node in enumerate(g1.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_01[node]] = {'label_gt':node}
nx.set_node_attributes(g1,dict_lab)

dict_lab = {}
for n, node in enumerate(g2.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_02[node]] = {'label_gt':node}
nx.set_node_attributes(g2,dict_lab)

dict_lab = {}
for n, node in enumerate(g3.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_03[node]] = {'label_gt':node}
nx.set_node_attributes(g3,dict_lab)

dict_lab = {}
for n, node in enumerate(g4.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[gt_04[node]] = {'label_gt':node}
nx.set_node_attributes(g4,dict_lab)

dict_lab = {}
for n, node in enumerate(g.nodes):
    if node >=20:
        dict_lab[node] = {'label_gt':outliers_label}
    else:
        dict_lab[node] = {'label_gt':node}
nx.set_node_attributes(g,dict_lab)

In [27]:
gx = nx.relabel.convert_node_labels_to_integers(g1)
gx.nodes(data=True)

NodeDataView({0: {'coord': array([-32.62546432, -30.49374769, -89.47463568]), 'label_gt': 6}, 1: {'coord': array([ 94.90147083, -23.6980305 ,  20.78735637]), 'label_gt': -1}, 2: {'coord': array([-74.54044656,  50.24596227,  43.80713528]), 'label_gt': -1}, 3: {'coord': array([43.90688274, 88.12676938, 17.48880118]), 'label_gt': 4}, 4: {'coord': array([ -9.28207078, -99.25978348,   7.83189291]), 'label_gt': 0}, 5: {'coord': array([ 48.60140059, -44.88430711, -74.98868472]), 'label_gt': -1}, 6: {'coord': array([ 69.77960989, -71.60871737,   1.73136945]), 'label_gt': 8}, 7: {'coord': array([-70.28062179,  70.62715071,   8.51115645]), 'label_gt': 7}, 8: {'coord': array([-52.34375377, -22.393685  ,  82.21103523]), 'label_gt': -1}, 9: {'coord': array([ 16.76202035, -36.18698447,  91.70352681]), 'label_gt': 9}, 10: {'coord': array([-49.17804745,  82.07633359, -29.06879965]), 'label_gt': -1}, 11: {'coord': array([ 73.934375  , -28.16643084,  61.15848565]), 'label_gt': 13}, 12: {'coord': array([

In [28]:
H = nx.Graph()
H.add_nodes_from(sorted(g1.nodes(data=True)))
H.add_edges_from(g1.edges(data=True))

In [42]:
# path_sorted = "/home/rohit/PhD_Work/GM_my_version/final_new_simu/0/Graph_relabeled/graphs"
# list_graphs_sorted = gp.load_graphs_in_list(path_sorted)

# g_sorted = list_graphs_sorted[4]

# g_sorted.nodes

In [29]:
# nx.get_node_attributes(g,'coord').values()

In [28]:
for ind in gt_02:
    print(g2.nodes.data()[ind])

{'coord': array([ -8.69066969, -99.61347477,   1.27589359]), 'label_gt': 0}
{'coord': array([-14.81124884,  64.91184598,  74.61286189]), 'label_gt': 1}
{'coord': array([-20.8787086 ,  96.16820935,  17.76949741]), 'label_gt': 2}
{'coord': array([-36.94592117, -51.91923021,  77.06745385]), 'label_gt': 3}
{'coord': array([41.32935546, 87.95926412, 23.55954653]), 'label_gt': 4}
{'coord': array([ 24.9600015 , -95.36526599,  16.80667626]), 'label_gt': 5}
{'coord': array([-31.12708379, -22.97149931, -92.21396247]), 'label_gt': 6}
{'coord': array([-69.51994188,  71.01383314,  11.13612074]), 'label_gt': 7}
{'coord': array([ 72.6356404 , -68.25163855,   8.11033772]), 'label_gt': 8}
{'coord': array([ 14.00324755, -36.50232723,  92.04069298]), 'label_gt': 9}
{'coord': array([-47.84250124, -84.70940554, -23.13896472]), 'label_gt': 10}
{'coord': array([-84.20397703,  -4.44431723, -53.75814632]), 'label_gt': 11}
{'coord': array([-94.73367317,  31.29147907,  -6.80988295]), 'label_gt': 12}
{'coord': ar

In [10]:
sphere_mesh = sio.load_mesh(file_sphere_mesh)
mesh = gv.reg_mesh(sio.load_mesh(file_template_mesh))
gp.sphere_nearest_neighbor_interpolation(g, sphere_mesh)
gp.sphere_nearest_neighbor_interpolation(g1, sphere_mesh)

In [179]:
nodes_coords = gp.graph_nodes_to_coords(g, 'ico100_7_vertex_index', sphere_mesh)
nodes_coords_1 = gp.graph_nodes_to_coords(g1, 'ico100_7_vertex_index', sphere_mesh)

In [23]:
counter = 0
rest = []
for i in range(len(g.nodes)):
    for ind in gt_01:
        if(g.nodes.data()[i]['label_gt'] == g1.nodes.data()[ind]['label_gt']):
            print(g.nodes.data()[i]['coord'],g1.nodes.data()[ind]['coord'])
            counter+=1
print(counter)

[ -8.29375734 -99.58600481   3.72038116] [ -9.28207078 -99.25978348   7.83189291]
[-11.96701424  65.4787652   74.62788941] [-19.39228571  69.60576829  69.13014014]
[-25.06130415  95.60418922  15.2239955 ] [-25.30512161  95.67896948  14.32430169]
[-36.95462701 -52.8159162   76.45151757] [-42.55639928 -54.45934114  72.27124631]
[42.60480034 87.95995566 21.16310915] [43.90688274 88.12676938 17.48880118]
[ 24.36019656 -95.13667031  18.85722104] [ 28.26062488 -93.99886388  19.11937947]
[-30.4412485  -26.82708365 -91.39823835] [-32.62546432 -30.49374769 -89.47463568]
[-70.04157873  70.43770444  11.51985424] [-70.28062179  70.62715071   8.51115645]
[ 71.22425583 -70.1867875    0.95929233] [ 69.77960989 -71.60871737   1.73136945]
[ 16.29928024 -35.40847182  92.09002979] [ 16.76202035 -36.18698447  91.70352681]
[-50.03733913 -84.16323567 -20.31783587] [-47.92418327 -83.28190631 -27.70192662]
[-83.34326539  -7.02261683 -54.81407635] [-79.55158573 -11.21003384 -59.54729506]
[-93.32844935  35.8005

In [15]:
un = nx.disjoint_union(g,g1)

In [40]:
for i in un.nodes():
    if((un.nodes.data()[i]['label']==50)):
       print(un.nodes.data()[i]['coord'])

[-56.11889642  25.04223002 -78.88951883]
[  2.77552172  97.88816609 -20.25347916]
[90.66891087 41.1681157  -9.18340084]
[-59.3130305   62.22627475  51.08674138]
[-16.49106543 -91.55535387  36.68326511]
[ 33.0934391  -78.95991037 -51.67356038]
[99.23325098 -8.58575806  8.89081878]
[62.88857825 58.68303726 51.00321424]
[ 76.43996182 -59.14811233 -25.65995021]
[-41.37398695 -14.95721347  89.80242184]
[-56.01050275 -81.91700632  12.34615961]
[  2.33495907 -88.65652333  46.20139432]
[ 34.32323732 -81.26778022 -47.0899488 ]
[ 24.10658203  22.49024288 -94.40901269]
[-30.7927306   65.37255605  69.12479047]
[ 50.5466927   38.5684428  -77.18488892]


In [28]:
gt = nx.read_gpickle('../data/simu_graph/varied_outliers/0/noise_1400,outliers_20/ground_truth.gpickle')
path_to_graphs = '../data/simu_graph/varied_outliers/0/noise_1400,outliers_20/graphs/'
path_to_groundtruth_ref = '../data/simu_graph/varied_outliers/0/noise_1400,outliers_20/permutation_to_ref_graph.gpickle'

In [7]:
gt_np = np.load('new_groundtruth.npy',allow_pickle=True)

In [8]:
gt_np

array([{2: 2, 5: 5, 10: 10, 11: 11, 12: 12, 14: 14},
       {2: 16, 5: 15, 10: 3, 11: 5, 14: 14}, {5: 12, 12: 10},
       {5: 18, 10: 10, 11: 13, 14: 16}], dtype=object)

In [10]:
gt['0,1']

{0: 8, 1: 5, 4: 9, 7: 7, 11: 13, 12: 1}

In [12]:
graphs = nx.read_gpickle('test_graphs.gpickle')

In [16]:
nx.number_of_nodes(graphs[3])

21

In [17]:
graphs

In [19]:
gt['0,0']

{0: 0,
 1: 1,
 2: 2,
 4: 4,
 5: 5,
 7: 7,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 20: 20}

In [20]:
gt_np

array([{2: 2, 5: 5, 10: 10, 11: 11, 12: 12, 14: 14},
       {2: 16, 5: 15, 10: 3, 11: 5, 14: 14}, {5: 12, 12: 10},
       {5: 18, 10: 10, 11: 13, 14: 16}], dtype=object)

In [36]:
gt['0,1'].values()

dict_values([8, 5, 9, 7, 13, 1])

In [25]:
gt['1,0']

{1: 12, 5: 1, 7: 7, 8: 0, 9: 4, 13: 11}

In [29]:
graph_meta = dataset_metadata(path_to_graphs, path_to_groundtruth_ref)

In [50]:
graph_meta.list_graphs[0].nodes

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20))

In [34]:
graph_meta.list_graphs[1].nodes[8]['coord']

array([ 17.90027139,  -8.06158098, -98.05402183])

In [47]:
keys = list(gt['0,4'].keys())
values = list(gt['0,4'].values())

for i in range(len(keys)):
    print(graph_meta.list_graphs[0].nodes[keys[i]]['coord'],',',graph_meta.list_graphs[4].nodes[values[i]]['coord'])

[-86.70725713  14.81492383 -47.56437314] , [-86.11821061  12.82054749 -49.18625176]
[-96.49010242 -24.15263509 -10.31069118] , [-95.96633242 -26.57140722  -9.1882186 ]
[-69.95263027  22.99781812  67.65892314] , [-71.15703826  21.60874631  66.85609912]


In [52]:
gt_np

array([{2: 2, 5: 5, 10: 10, 11: 11, 12: 12, 14: 14},
       {2: 16, 5: 15, 10: 3, 11: 5, 14: 14}, {5: 12, 12: 10},
       {5: 18, 10: 10, 11: 13, 14: 16}], dtype=object)

In [55]:
gt['0,0']

{0: 0,
 1: 1,
 2: 2,
 4: 4,
 5: 5,
 7: 7,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 20: 20}

In [56]:
gt['0,1']

{0: 8, 1: 5, 4: 9, 7: 7, 11: 13, 12: 1}

In [57]:
gt['0,2']

{10: 9, 12: 10, 14: 8, 15: 1}

In [58]:
gt['0,3']

{0: 15, 1: 1, 2: 9, 12: 3, 13: 22, 20: 19}

In [59]:
gr_ralabelled = nx.read_gpickle('OAS1_0004_lh_pitgraph.gpickle')

In [62]:
gr_ralabelled.nodes[0]

{'vertex_index': 5843,
 'sphere_3dcoords': [34.887020111083984,
  -85.88994598388672,
  37.494171142578125],
 'sphere_coords': [-1.1849713325500488, 1.18646240234375],
 'basin_label': 392.0,
 'basin_area': 62.435993,
 'depth': 0.8423674,
 'basin_thickness': 2.4124622344970703,
 'ico100_7_vertex_index': 2764,
 'label_neuroimage': 139,
 'label_media': 91,
 'sphere_3dcoords_noreg': array([ 34.54939, -90.6821 ,  24.14739], dtype=float32),
 'ico100_7_vertex_index_noreg': 30596}

In [112]:
 subjects_list = ['OAS1_0006', 'OAS1_0009', 'OAS1_0025', 'OAS1_0049', 'OAS1_0051', 'OAS1_0054', 'OAS1_0055',
                     'OAS1_0057', 'OAS1_0059', 'OAS1_0061', 'OAS1_0077', 'OAS1_0079', 'OAS1_0080', 'OAS1_0087',
                     'OAS1_0104', 'OAS1_0125', 'OAS1_0136', 'OAS1_0147', 'OAS1_0150', 'OAS1_0151', 'OAS1_0152',
                     'OAS1_0156', 'OAS1_0162', 'OAS1_0191', 'OAS1_0192', 'OAS1_0193', 'OAS1_0202', 'OAS1_0209',
                     'OAS1_0218', 'OAS1_0224', 'OAS1_0227', 'OAS1_0231', 'OAS1_0236', 'OAS1_0239', 'OAS1_0246',
                     'OAS1_0249', 'OAS1_0253', 'OAS1_0258', 'OAS1_0294', 'OAS1_0295', 'OAS1_0296', 'OAS1_0310',
                     'OAS1_0311', 'OAS1_0313', 'OAS1_0325', 'OAS1_0348', 'OAS1_0379', 'OAS1_0386', 'OAS1_0387',
                     'OAS1_0392', 'OAS1_0394', 'OAS1_0395', 'OAS1_0397', 'OAS1_0406', 'OAS1_0408', 'OAS1_0410',
                     'OAS1_0413', 'OAS1_0415', 'OAS1_0416', 'OAS1_0417', 'OAS1_0419', 'OAS1_0420', 'OAS1_0421',
                     'OAS1_0431', 'OAS1_0437', 'OAS1_0442', 'OAS1_0448', 'OAS1_0004', 'OAS1_0005', 'OAS1_0007',
                     'OAS1_0012', 'OAS1_0017', 'OAS1_0029', 'OAS1_0037', 'OAS1_0043', 'OAS1_0045', 'OAS1_0069',
                     'OAS1_0090', 'OAS1_0092', 'OAS1_0095', 'OAS1_0097', 'OAS1_0101', 'OAS1_0102', 'OAS1_0105',
                     'OAS1_0107', 'OAS1_0108', 'OAS1_0111', 'OAS1_0117', 'OAS1_0119', 'OAS1_0121', 'OAS1_0126',
                     'OAS1_0127', 'OAS1_0131', 'OAS1_0132', 'OAS1_0141', 'OAS1_0144', 'OAS1_0145', 'OAS1_0148',
                     'OAS1_0153', 'OAS1_0174', 'OAS1_0189', 'OAS1_0211', 'OAS1_0214', 'OAS1_0232', 'OAS1_0250',
                     'OAS1_0261', 'OAS1_0264', 'OAS1_0277', 'OAS1_0281', 'OAS1_0285', 'OAS1_0302', 'OAS1_0314',
                     'OAS1_0318', 'OAS1_0319', 'OAS1_0321', 'OAS1_0328', 'OAS1_0333', 'OAS1_0340', 'OAS1_0344',
                     'OAS1_0346', 'OAS1_0350', 'OAS1_0359', 'OAS1_0361', 'OAS1_0368', 'OAS1_0370', 'OAS1_0376',
                     'OAS1_0377', 'OAS1_0385', 'OAS1_0396', 'OAS1_0403', 'OAS1_0409', 'OAS1_0435', 'OAS1_0439',
                     'OAS1_0450']


In [113]:
len(subjects_list)

134

In [68]:
list(gt['0,1'].keys())[list(gt['0,1'].values()).index(9)]

4

In [66]:
gt['0,1']

{0: 8, 1: 5, 4: 9, 7: 7, 11: 13, 12: 1}

In [110]:
g = graph_meta.list_graphs[0]
g1 = graph_meta.list_graphs[1]
g2 = graph_meta.list_graphs[2]
g3 = graph_meta.list_graphs[3]

In [ ]:
# dict_lab = {}
# for n, node in enumerate(g.nodes):
#     dict_lab[node] = {'label_gt':node}
#     nx.set_node_attributes(g,dict_lab)

In [116]:
dict_lab = {}
outliers_label = -1
for n, node in enumerate(g3.nodes):
    
    if node not in list(gt['0,3'].values()):
        dict_lab[node] = {'label_gt':outliers_label}
        
    else:
        dict_lab[node] = {'label_gt':list(gt['0,3'].keys())[list(gt['0,3'].values()).index(node)]}
nx.set_node_attributes(g3,dict_lab)

In [117]:
for i in range(len(g.nodes)):
    for j in range(len(g3.nodes)):
        
        if g.nodes[0]['label_gt'] != -1:
            
            if g.nodes[i]['label_gt'] == g3.nodes[j]['label_gt']:
                print(g.nodes[i]['coord'], ' ' , g3.nodes[j]['coord'])

[ 14.58532114  -5.12506017 -98.79778421]   [ 13.55297962  -9.00563561 -98.6671945 ]
[-11.22894047 -92.56684454  36.12879998]   [ -8.4921932  -92.18619107  37.80990388]
[ 64.40511785 -68.54639384  33.96134106]   [ 63.74409088 -68.86655691  34.55558157]
[-96.49010242 -24.15263509 -10.31069118]   [-96.87492333 -20.37937877 -14.13966588]
[-69.95263027  22.99781812  67.65892314]   [-67.65952001  24.79684514  69.33473749]
[43.50568703 58.84165088 68.15361559]   [43.57118436 62.93689438 64.34671102]
